### ISSUE TITLE
initial load to trakt/letterboxd

### ISSUE THREAD

**Issue by thobi85** [JvSomeren/tautulli-watched-sync#7]
Hello,
first of all thank you for this script.
I would like to use it for my plex/tautulli setup. Is it possible beside the tautulli trigger "watched" to have an initial load for the already watched episodes and movies?

regards
thobi

**Comment by JvSomeren** [comment]
It should be possible to build something like that using Tautulli's API ([get_history](https://github.com/Tautulli/Tautulli/wiki/Tautulli-API-Reference#get_history) for example).

However the script in its current state doesn't support is. It was made to receive events from Tautulli not query it for data.

**Comment by thobi85** [comment]
Thanks for your reply.
I have also checked the tautulli API at the weekend and developed an initial load for movies and episodes with the methods get_history and get_metadata to sync them to Trakt.
The initial load can be triggered like you trigger the letterboxd authentication.

**Comment by Anon0511** [comment]
> Thanks for your reply. I have also checked the tautulli API at the weekend and developed an initial load for movies and episodes with the methods get_history and get_metadata to sync them to Trakt. The initial load can be triggered like you trigger the letterboxd authentication.

Hey, you got some code to share?

**Comment by thobi85** [comment]
> Hey, you got some code to share?

I can fork it and make it available on my own github. I have additionally changed from tvdb to tmdb id's.
Give me a few days to go through the coding and upload it.

**Comment by Anon0511** [comment]
> > Hey, you got some code to share?
> 
> I can fork it and make it available on my own github. I have additionally changed from tvdb to tmdb id's. Give me a few days to go through the coding and upload it.

Thanks, that would be great. I tried an hour with ChatGPT to get it working but to no avail.

**Comment by thobi85** [comment]
> Thanks, that would be great. I tried an hour with ChatGPT to get it working but to no avail.

Good for me, that ChatGPT can't solve any coding topics yet. ;-)
I have forked the script, added my adjustment and have also done some improvement.
I didn't have the change to test it. Please provide me feedback if everything work or if I need some changes.

**Comment by Anon0511** [comment]
```
root@4d17985e1c5f:/config/scripts# python ./trakt_sync.py --contentType initial --userId -1
Traceback (most recent call last):
  File "/config/scripts/./trakt_sync.py", line 436, in <module>
    initial.initial_load()
  File "/config/scripts/./trakt_sync.py", line 337, in initial_load
    tautulli_url = self.get_tautulli_url()
                   ^^^^
NameError: name 'self' is not defined
```

You might enable issues in your repo and we can move the topic there. :)

**Comment by thobi85** [comment]
> You might enable issues in your repo and we can move the topic there. :)

I have enabled the issues and have also done some adjustments on the script.
You had also some requests in the plextraktsync script, right?

**Comment by Bruxes** [comment]
Would be cool to also sync ratings.
